# -*- coding: utf-8 -*-
"""equity backtest.ipynb

Automatically generated by Colab.

This file was written with Jupyter. However, due to upload error with Github, it is uploaded with .py.
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()
df = pd.read_excel("aapl_03152025_04152026.xlsx")

df=df[df['volume']!=0]
df.reset_index(drop=True, inplace=True)
df.isna().sum()
df.tail()

def calculate_atr(df, period=14):
    high = df['high']
    low = df['low']
    close = df['close']

    tr = pd.Series(index=df.index, dtype=float)

    tr.iloc[0] = high.iloc[0] - low.iloc[0]
    for i in range(1, len(df)):
        tr.iloc[i] = max(
            high.iloc[i] - low.iloc[i],
            abs(high.iloc[i] - close.iloc[i-1]),
            abs(low.iloc[i] - close.iloc[i-1])
        )

    atr = tr.rolling(period).mean()
    return atr

import os

df['ATR'] = calculate_atr(df, period=14)
curr_dir = os.getcwd()
df.to_excel(os.path.join(curr_dir, "ATR.xlsx"), index=False)

# Support and Resistance FUNCTIONS
def support(df1, l, n1, n2): #n1 n2 before and after candle l
    for i in range(l-n1+1, l+1):
        if(df1.low[i]>df1.low[i-1]):
            return 0
    for i in range(l+1,l+n2+1):
        if(df1.low[i]<df1.low[i-1]):
            return 0
    return 1

def resistance(df1, l, n1, n2): #n1 n2 before and after candle l
    for i in range(l-n1+1, l+1):
        if(df1.high[i]<df1.high[i-1]):
            return 0
    for i in range(l+1,l+n2+1):
        if(df1.high[i]>df1.high[i-1]):
            return 0
    return 1

length = len(df)
high = list(df['high'])
low = list(df['low'])
close = list(df['close'])
open = list(df['open'])
atr = list(df['ATR'])

bodydiff = [0] * length
highdiff = [0] * length
lowdiff = [0] * length
ratio1 = [0] * length
ratio2 = [0] * length

def isEngulfing(l):
    bodydiff[l] = abs(open[l] - close[l])

    if bodydiff[l] < 0.1 * atr[l]:
        bodydiff[l] = 0.1 * atr[l]

    bodydiffmin = 0.35 * atr[l]

    # Bearish engulfing
    if (bodydiff[l] > bodydiffmin and
        bodydiff[l-1] > bodydiffmin and
        open[l-1] < close[l-1] and
        open[l] > close[l] and
        open[l] - close[l-1] >= -0.2 * atr[l] and
        close[l] < open[l-1]):
        return 1

    # Bullish engulfing
    elif (bodydiff[l] > bodydiffmin and
          bodydiff[l-1] > bodydiffmin and
          open[l-1] > close[l-1] and
          open[l] < close[l] and
          open[l] - close[l-1] <= 0.2 * atr[l] and
          close[l] > open[l-1]):
        return 2

    return 0

def isStar(l):
    bodydiffmin = 0.35 * atr[l]

    highdiff[l] = high[l] - max(open[l], close[l])
    lowdiff[l] = min(open[l], close[l]) - low[l]
    bodydiff[l] = abs(open[l] - close[l])

    if bodydiff[l] < 0.1 * atr[l]:
        bodydiff[l] = 0.1 * atr[l]

    ratio1[l] = highdiff[l] / bodydiff[l]
    ratio2[l] = lowdiff[l] / bodydiff[l]

    # Bearish shooting star
    if ratio1[l] > 1.5 and lowdiff[l] < 0.3 * highdiff[l] and bodydiff[l] > bodydiffmin:
        return 1

    # Bullish hammer
    if ratio2[l] > 1.5 and highdiff[l] < 0.3 * lowdiff[l] and bodydiff[l] > bodydiffmin:
        return 2

    return 0

def closeResistance(l, levels):
    if not levels:
        return 0

    lim = 1 * atr[l]
    level = min(levels, key=lambda x: abs(x - high[l]))

    return (
        abs(high[l] - level) <= lim and
        min(open[l], close[l]) < level and
        low[l] < level)


def closeSupport(l, levels):
    if not levels:
        return 0

    lim = 1.5 * atr[l]
    level = min(levels, key=lambda x: abs(x - low[l]))

    return (
        abs(low[l] - level) <= lim and
        max(open[l], close[l]) > level and
        high[l] > level)

n1 = 2
n2 = 2
backCandles = 30

signal = [0] * length

for row in range(backCandles, length - n2):
    ss, rr = [], []

    for subrow in range(row - backCandles + n1, row + 1):
        if support(df, subrow, n1, n2):
            ss.append(low[subrow])
        if resistance(df, subrow, n1, n2):
            rr.append(high[subrow])


    if (isEngulfing(row) == 1 or isStar(row) == 1) and (closeResistance(row, rr) or len(rr) >= 1):
        signal[row] = 1  # sell

    elif (isEngulfing(row) == 2 or isStar(row) == 2) and (closeSupport(row, ss) or len(ss) >= 1):
        signal[row] = 2  # buy

df['signal']=signal
df[df['signal']==2].count()

import os

df.columns = ['Local time', 'Open', 'High', 'Low', 'Close', 'Volume', 'ATR', 'signal']
df['Local time'] = pd.to_datetime(df['Local time'])
df.set_index('Local time', inplace=True, drop=False)

df

!pip install backtesting

from backtesting import Strategy, Backtest
from backtesting import set_bokeh_output

set_bokeh_output(notebook=False)

def SIGNAL():
    return df.signal

class MyCandlesStrat(Strategy):
    def init(self):
        self.signal1 = self.I(SIGNAL)
        self.atr = self.data.ATR

    def next(self):
        atr = self.atr[-1]

        if self.signal1[-1] == 2 and not self.position:
            self.buy(
                sl=self.data.Close[-1] - atr,
                tp=self.data.Close[-1] + 1.5 * atr
            )

        elif self.signal1[-1] == 1 and not self.position:
            self.sell(
                sl=self.data.Close[-1] + atr,
                tp=self.data.Close[-1] - 1.5 * atr
            )

bt = Backtest(df, MyCandlesStrat, cash=10_000, commission=.002)
stat = bt.run()
stat

from backtesting import set_bokeh_output
from bokeh.io import output_notebook

output_notebook()
set_bokeh_output(notebook=True)
bt.plot()
